export const children = {
    id: "enfants",
    title: "La prise en charge ostéopathique des enfants & adolescents",
    intro: `L'ostéopathie chez les enfants et adolescents est adaptée et recommandée pour différents motifs semblables à l'adulte. Cependant, des troubles de la statique sont plus fréquents à ces âges comme risque de lordoses et dysfonctions au niveau des courbures rachidiennes. Elles sont souvent dues à une mauvaise adaptation du corps par rapport à la croissance ou bien encore des troubles posturaux avec les sacs à dos lourd et mauvaise assise pendant les cours.`,
    subtext1: `Votre ostéopathe Charles Dumeige emploiera des techniques ostéopathiques adaptées en fonction de l'âge (3-14 ans pour les enfants et 14-18 ans pour les adolescents). Il vous procurera des conseils au niveau hygiéno-diététique (pratiquer un sport régulier par exemple) ou encore vous expliquera les gestes et postures afin d'éviter ses troubles de la statique.`,
    subtext2: `
Il est recommandé de consulter une fois par an maximum, en fonction des besoins de l'enfant (bien rester attentif à ses plaintes et anticiper l'apparition de douleurs associées). Un parent devra être obligatoirement présent lors de la consultation et des conseils lui seront donnés également pour sensibiliser à surveiller l'évolution de la croissance de l'enfant. En effet, il devra surveiller l'évolution des courbures rachidiennes afin de détecter des possibles apparition de scoliose, pour qu'une prise en charge multidisciplinaire adaptée soit mise en place avant un stade trop avancé (séances de kinésithérapeute fortement recommandées à ce moment là en complément). L'ostéopathie participe à l'efficacité et à la stabilité du traitement. `,
    subtext3: `La vie de l'enfant et adolescents est mouvementée, elle est sujet à la pratique d'activités sportives, où ils peuvent subir des traumatismes et chutes à répétition. Suites à cela, il peut y avoir des tensions tissulaires qui restent et peuvent se réveiller plus tard à cause de la mémoire traumatique.\n 
Pour que la croissance se fasse plus harmonieuse, et aider le corps à se rétablir face aux traumatismes, un suivi ostéopathique régulier est important lors d'une pratique d'activité sportive régulière ou une activité source de micro-traumatismes (rugby, arts martiaux, équitation).`,
    img: require("../assets/photo-gallery/child-1.jpg"),
    img2: require("../assets/photo-gallery/child-2.jpg"),
}